site_name: "aws-sm-buildkite-plugin"
site_description: "Buildkite plugin for working with AWS Secrets Manager"

plugins:
  - techdocs-core

# ---
#  With `nav` commented out mkdocs will genetrate a list of all the files in the docs folder automatically
#  Uncomment it to overwrite this behaviors and build your own navigation tree
# ---
# nav:
#   - Home: index.md
